### ISSUE TITLE
cannot read 'selected_wallet' of null error encountered

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#131]
```
TypeError: Cannot read property 'selected_wallet' of null
    at Wallet.render (http://localhost:1212/dist/renderer.dev.js:12853:29)
    at finishClassComponent (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:14741:31)
    at updateClassComponent (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:14696:24)
    at beginWork (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:15644:16)
    at performUnitOfWork (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19312:12)
    at workLoop (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19352:24)
    at renderRoot (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19435:7)
    at performWorkOnRoot (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20342:7)
    at performWork (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20254:7)
    at performSyncWork (/Users/glendc/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20228:3)
```

https://github.com/threefoldfoundation/tfchain-wallet-electron/blob/94883f41d8e7c95359810dded38c7af975bea8da/app/components/wallet/Wallet.js#L71-L75

Seems that account on Line 72 is null, making this crash to the app home page.

**Comment by GlenDC** [comment]
Seems the account=null bug of earlier today is not completely solved yet...

<img width="803" alt="Screenshot 2019-06-17 at 22 38 59" src="https://user-images.githubusercontent.com/3900482/59635145-bdd86f00-9150-11e9-8427-cd97da722f55.png">

**Comment by GlenDC** [comment]
https://github.com/threefoldfoundation/tfchain-wallet-electron/blob/1351552641b9dcfa66a6728231f7b1d14bf84aa0/app/actions/index.js#L92-L98

> ^ is still there. I thought you deleted this part of the code to fix this type of error @DylanVerstraete, why is it still there? Isn't this what causes this issue as well?
