### ISSUE TITLE
moment().zone deprecation warning

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#44]
```
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: -120
Error
    at Moment.zone ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/moment/moment.js:320:98)
    at Footer.render (http://localhost:1212/dist/renderer.dev.js:4735:96)
    at finishClassComponent ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:14741:31)
    at updateClassComponent ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:14696:24)
    at beginWork ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:15644:16)
    at performUnitOfWork ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19312:12)
    at workLoop ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19352:24)
    at renderRoot ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19435:7)
    at performWorkOnRoot ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20342:7)
    at performWork ($HOME/oss/github.com/threefoldfoundation/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20254:7)
```

**Comment by DylanVerstraete** [comment]
closed in https://github.com/threefoldfoundation/tfchain-wallet-electron/commit/6ad0b174221ae7432954478133f2d0685abb9c27
